"use client";
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer,
  PieChart, Pie, Cell,
} from "recharts";
import { Database, Cpu, Target, TrendingUp } from "lucide-react";

const TRAFFIC_DIST = [
  { category: "Benign",     packets: 2030000, color: "#00d4ff" },
  { category: "DoS / DDoS", packets: 750000,  color: "#ff2244" },
  { category: "Brute Force",packets: 158930,  color: "#f59e0b" },
  { category: "PortScan",   packets: 122104,  color: "#a855f7" },
  { category: "Infiltration",packets: 36569,  color: "#ec4899" },
  { category: "Web Attacks", packets: 2180,   color: "#f97316" },
  { category: "Heartbleed",  packets: 11,     color: "#64748b" },
];

const PIE_DATA = [
  { name: "Normal Traffic", value: 72.3, color: "#00d4ff" },
  { name: "DDoS/Malicious", value: 27.7, color: "#ff2244" },
];

const KPIS = [
  { icon: <Database className="w-5 h-5" />, label: "Total Packets", value: "2.83M", sub: "CICIDS2017 dataset" },
  { icon: <TrendingUp className="w-5 h-5" />, label: "Network Features", value: "80+", sub: "Flow characteristics" },
  { icon: <Cpu className="w-5 h-5" />, label: "ML Detection Accuracy", value: "99.7%", sub: "Random Forest model" },
  { icon: <Target className="w-5 h-5" />, label: "False Positive Rate", value: "0.012%", sub: "Industry-leading precision" },
];

const BAR_DATA = [
  { label: "Mon", normal: 420, malicious: 80 },
  { label: "Tue", normal: 380, malicious: 210 },
  { label: "Wed", normal: 510, malicious: 340 },
  { label: "Thu", normal: 290, malicious: 520 },
  { label: "Fri", normal: 600, malicious: 180 },
  { label: "Sat", normal: 340, malicious: 90 },
  { label: "Sun", normal: 410, malicious: 60 },
];

export default function DatasetModule() {
  return (
    <section id="dataset" className="max-w-6xl mx-auto px-4 py-20 section-enter">
      <div className="text-center mb-12">
        <span className="inline-block px-3 py-1 rounded-full text-xs font-semibold bg-blue-500/10 text-blue-400 border border-blue-500/20 mb-4">MODULE 4 · ACADEMIC DATASET</span>
        <h2 className="text-4xl md:text-5xl font-black text-white mb-4">
          CICIDS<span className="gradient-text">2017</span> Dataset
        </h2>
        <p className="text-slate-400 text-lg max-w-3xl mx-auto">
          Real-world network intrusion detection dataset used to train modern AI-powered security systems.
          Generated by the Canadian Institute for Cybersecurity.
        </p>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-10">
        {KPIS.map(k => (
          <div key={k.label} className="glass-panel p-5 hover-card glow-cyan">
            <div className="text-cyan-400 mb-3">{k.icon}</div>
            <div className="text-3xl font-black text-white mb-1">{k.value}</div>
            <div className="text-sm font-semibold text-slate-300">{k.label}</div>
            <div className="text-xs text-slate-500 mt-1">{k.sub}</div>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
        {/* Bar Chart */}
        <div className="glass-panel p-6">
          <h3 className="text-white font-bold mb-1">Traffic Category Distribution</h3>
          <p className="text-slate-500 text-xs mb-5">Packet count by traffic class in CICIDS2017</p>
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={TRAFFIC_DIST} layout="vertical" margin={{ left: 10, right: 10 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" horizontal={false} />
              <XAxis type="number" tick={{ fill: "#475569", fontSize: 10 }} tickFormatter={v => `${(v/1000).toFixed(0)}k`} />
              <YAxis dataKey="category" type="category" tick={{ fill: "#94a3b8", fontSize: 11 }} width={90} />
              <Tooltip
                contentStyle={{ background: "#0d1b35", border: "1px solid #1e3a5f", borderRadius: 8, fontSize: 12 }}
                formatter={(v: number) => [v.toLocaleString(), "Packets"]}
              />
              <Bar dataKey="packets" radius={[0, 4, 4, 0]}>
                {TRAFFIC_DIST.map((d, i) => <Cell key={i} fill={d.color} />)}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>

        {/* Pie + Weekly Bar */}
        <div className="flex flex-col gap-6">
          <div className="glass-panel p-6 flex-1">
            <h3 className="text-white font-bold mb-1">Normal vs. Malicious Ratio</h3>
            <p className="text-slate-500 text-xs mb-3">Overall traffic composition</p>
            <div className="flex items-center gap-6">
              <ResponsiveContainer width="50%" height={150}>
                <PieChart>
                  <Pie data={PIE_DATA} cx="50%" cy="50%" outerRadius={60} dataKey="value" strokeWidth={0}>
                    {PIE_DATA.map((d, i) => <Cell key={i} fill={d.color} />)}
                  </Pie>
                  <Tooltip contentStyle={{ background: "#0d1b35", border: "1px solid #1e3a5f", borderRadius: 8, fontSize: 11 }} formatter={(v: number) => [`${v}%`, ""]} />
                </PieChart>
              </ResponsiveContainer>
              <div className="space-y-3">
                {PIE_DATA.map(d => (
                  <div key={d.name} className="flex items-center gap-2">
                    <div className="w-3 h-3 rounded-full flex-shrink-0" style={{ background: d.color }} />
                    <div>
                      <div className="text-white text-sm font-bold">{d.value}%</div>
                      <div className="text-slate-400 text-xs">{d.name}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          <div className="glass-panel p-6 flex-1">
            <h3 className="text-white font-bold mb-1">Attack Volume by Day</h3>
            <p className="text-slate-500 text-xs mb-3">Simulated weekly capture window</p>
            <ResponsiveContainer width="100%" height={130}>
              <BarChart data={BAR_DATA}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
                <XAxis dataKey="label" tick={{ fill: "#475569", fontSize: 10 }} />
                <YAxis tick={{ fill: "#475569", fontSize: 10 }} />
                <Tooltip contentStyle={{ background: "#0d1b35", border: "1px solid #1e3a5f", borderRadius: 8, fontSize: 11 }} />
                <Bar dataKey="normal" name="Normal" fill="#00d4ff" radius={[2,2,0,0]} />
                <Bar dataKey="malicious" name="Malicious" fill="#ff2244" radius={[2,2,0,0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* ML Models comparison */}
      <div className="glass-panel p-6 mb-6">
        <h3 className="text-white font-bold mb-4">ML Detection Model Comparison</h3>
        <div className="space-y-3">
          {[
            { model: "Random Forest",      accuracy: 99.7, color: "#00d4ff" },
            { model: "Neural Network",     accuracy: 98.9, color: "#a855f7" },
            { model: "Decision Tree",      accuracy: 97.8, color: "#00ff88" },
            { model: "KNN Classifier",     accuracy: 96.4, color: "#f59e0b" },
            { model: "Naïve Bayes",        accuracy: 88.2, color: "#94a3b8" },
          ].map(m => (
            <div key={m.model} className="flex items-center gap-4">
              <div className="w-36 text-sm text-slate-300 flex-shrink-0">{m.model}</div>
              <div className="flex-1 h-6 bg-slate-800 rounded-full overflow-hidden">
                <div className="h-full rounded-full flex items-center justify-end pr-2 transition-all duration-1000"
                  style={{ width: `${m.accuracy}%`, background: `linear-gradient(90deg, ${m.color}44, ${m.color})` }}>
                  <span className="text-white text-xs font-bold">{m.accuracy}%</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Footnote */}
      <div className="glass-panel p-5 border-l-4 border-blue-500">
        <p className="text-slate-400 text-sm leading-relaxed">
          <strong className="text-blue-400">📚 Academic Context:</strong> The CICIDS2017 and NSL-KDD datasets are industry-standard benchmarks for evaluating Network Intrusion Detection Systems (NIDS). 
          Captured over a full week on a realistic network topology, these datasets include both benign traffic and labeled attack categories (DoS, DDoS, Port Scan, Brute Force, Web Attacks, Infiltration, Heartbleed). 
          Modern security hardware — including next-generation firewalls and cloud-based WAFs — utilize ML models trained on these datasets to perform <strong className="text-cyan-400">automated, zero-day DDoS mitigation</strong> with sub-millisecond response times.
        </p>
      </div>
    </section>
  );
}
